allowBuilds:
  esbuild: true
  lightningcss: true
  better-sqlite3: true
  core-js: set this to true or false
minimumReleaseAgeExclude:
  - '@tanstack/query-core@5.104.1'
  - '@tanstack/query-devtools@5.104.1'
  - '@tanstack/react-query-devtools@5.104.1'
  - '@tanstack/react-query@5.104.1'
